spring:
  application:
    name: lab-4-article service

eureka:
  instance:
    preferIpAddress: false # book 108: register IP rather than service name
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
      
words: a,the

server:
  port: ${PORT:${SERVER_PORT:0}}