#spring:
#  application:
#    name: adjective
#  profiles:    
#      active:
#        default                

eureka:
  instance:
    preferIpAddress: false # book 108: register IP rather than service name
#  client:    
#    serviceUrl:
#      defaultZone: http://localhost:8010/eureka  # this will be obtained from config servier; see bootstrap.yml
      
#words: partially, awfully,extraordinarily,rather,incredible,vaunted,extremely


#server:
 # port: ${PORT:${SERVER_PORT:0}}