spring:
  application:
    name: lab-4-adjective service
    #profiles:
     # active: adjective
    
    

eureka:
  instance:
    preferIpAddress: false # book 108: register IP rather than service name
#  client:    
#    serviceUrl:
#      defaultZone: http://localhost:8010/eureka  # this will be obtained from config servier; see bootstrap.yml
      
#words: rather,incredible,vaunted,extremely

server:
  port: ${PORT:${SERVER_PORT:0}}