eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: ${PORT:${SERVER_PORT:0}}   # Select any available port if neither port nor server port are specified.

---

spring:
  profiles: adjone
words: one-partial,one-awful,one-rather,one-incredible

---

spring:
  profiles: adjtwo
words: two-partial,two-awful,two-rather,two-incredible  
