spring:
  application:
    name: LAB-4-NOUN SERVICE
    profiles:
      active: noun

eureka:
  instance:
    preferIpAddress: false # book 108: register IP rather than service name
# following are disabled, so client can get euraka serviceUrl from config server
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8010/eureka
      
#words: boat,book,vote,seat,backpack,partition,groundhog

server:
  port: ${PORT:${SERVER_PORT:0}}