spring:
  application:
    name: lab-4-sentence service

eureka:
  instance:
    preferIpAddress: false # book 108: register IP rather than service name
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
     

server:
  port: 8020